### ISSUE TITLE
Limits on selecting semester start date

### ISSUE THREAD

**Issue by MohAli360** [ElforL/AOU_schedule_manager#4]
The Start Date of the semester is limited to Sundays only; cannot select any day except Sunday
Here in Egypt Branch the start of the week is Saturday 
This Semester (Summer) we will start on Sat. 16 Jul 2022

**Comment by ElforL** [comment]
Fixed. 
The update is available on [Google Play][gplay].
Or you can download it using the `apk` in the [newest release](https://github.com/ElforL/AOU_schedule_manager/releases).

[gplay]: https://play.google.com/store/apps/details?id=com.Elfor.uni_assistant

**Comment by MohAli360** [comment]
Thanks 😊
